name: learn-github-actions
on: [push]
jobs: 
  echo-weird-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "ACTION COMPLETE"